train_samples_file_path: ./preprocessed_data/genia_train_config_genia_production_samples.json
valid_samples_file_path: ./preprocessed_data/genia_valid_config_genia_production_samples.json
test_samples_file_path: ./preprocessed_data/genia_test_config_genia_production_samples.json
types_file_path: ./preprocessed_data/genia_train_vanilla_types.txt
num_types: 5
dataset_name: genia
dataset_config_name: genia_config_vanilla
expected_number_of_train_samples: 9273
expected_number_of_valid_samples: 4636
expected_number_of_test_samples: 4637
