train_samples_file_path: ./preprocessed_data/ncbi_disease_train_config_ncbi_meta_all_mistakes_all_gold_production_samples.json
valid_samples_file_path: ./preprocessed_data/ncbi_disease_valid_config_ncbi_meta_all_mistakes_all_gold_production_samples.json
test_samples_file_path: ./preprocessed_data/ncbi_disease_test_config_ncbi_meta_all_mistakes_all_gold_production_samples.json
types_file_path: ./preprocessed_data/ncbi_disease_train_config_ncbi_meta_production_types.txt
num_types: 2
dataset_name: ncbi_disease
dataset_config_name: ncbi_disease_meta
expected_number_of_train_samples: 5548
expected_number_of_valid_samples: 980
expected_number_of_test_samples: 1044
